version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:latest
    container_name: app
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_TABLE: ${DB_TABLE}
    restart: unless-stopped
    volumes:
      - ./:/var/www

  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./:/var/www
      - ./config/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    container_name: pma

volumes:
  mysqldata: {}
