version: '3'

services:
  php:
    build: .
    container_name: php
    env_file:
      - &env .env
    volumes:
      - ./:/var/www
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/app.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - php
      - mysql

  mysql:
    image: mariadb
    container_name: db
    env_file:
      - *env
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  mysqldata: { }
